[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_swap_escrow = "DBdV6y5ZvfYNPRcMLgBDjrZ33x1DvKL9dy93LKNwE21p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
