[package]
name = "car-rental-service"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "=2.0.2"
shank = "0.4.2"

[lib]
crate-type = ["cdylib", "lib"]
