[package]
name = "create-token-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "2.0.2"
spl-token = { version = "4.0.0", features = [ "no-entrypoint" ] }
spl-associated-token-account = { version = "4.0.0", features = [ "no-entrypoint" ] }
mpl-token-metadata = { version = "4.1.2", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]
