[features]
seeds = true
skip-lint = false
[programs.localnet]
seahorse = "3ZckR8obvBASHPqWD6gcWgb8gCdw5UseJ7D1xFzxnZ4B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu-22/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
