[package]
name = "cross-program-invocatio-native-lever"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "=2.0.2"

[lib]
crate-type = ["cdylib", "lib"]
